### ISSUE TITLE
AWS keys should not be in secrets.yaml, AWS docs says it should be in .aws/credentials

### ISSUE THREAD

**Issue by alberttwong** [sborenst/ansible_aws_deployer#36]
See http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

**Comment by thoraxe** [comment]
You are conflating use of the env vars for Ansible with use of the AWS CLI, which are two different things.

**Comment by thoraxe** [comment]
FYI: https://github.com/sborenst/ansible_aws_deployer/blob/master/ansible/files/inventory_templates/hosts.bu-workshop.j2#L124-L125
